name: Docker CUDA Image Pull and Run

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 可选：如果是私有镜像需要登录 Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        if: secrets.DOCKER_HUB_PASSWORD != ''

      - name: Pull NVIDIA CUDA Docker Image
        run: docker pull nvidia/cuda:12.2.0-cudnn8-devel-ubuntu20.04

      - name: Run Docker Container
        run: |
          docker run nvidia/cuda:12.2.0-cudnn8-devel-ubuntu20.04 echo "Docker container is running"
