name: Docker CUDA Image Pull and Run

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull NVIDIA CUDA Docker Image
        run: docker pull nvidia/cuda:12.6.1-base-ubuntu20.04

      - name: Run Docker Container
        run: |
          docker run nvidia/cuda:12.6.1-base-ubuntu20.04 echo "Docker container is running"
