name: Docker CUDA Image Pull, Save and Upload

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull NVIDIA CUDA Docker Image
        run: docker pull nvidia/cuda:12.6.1-base-ubuntu20.04

      - name: Save Docker Image to .tar
        run: docker save nvidia/cuda:12.6.1-base-ubuntu20.04 -o cuda_image.tar

      - name: Upload Docker Image .tar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cuda-docker-image
          path: cuda_image.tar

